### ISSUE TITLE
关于shadowsocks的UDP通道串联UDPspeederv2的问题

### ISSUE THREAD

**Issue by thisdk** [honwen/luci-app-shadowsocks#1]
作者你好.感谢你写出几个那么棒的库.这半年我一直都是用你的库
现在我遇到一个问题.想请教你一下.

我最近在用shadowsocks的UDP来加速游戏.
但是因为我的服务器延迟很不稳定.偶尔还会丢包.所以我在你的库里面UDP通道串联了UDPspeederv2来多倍发包来稳定延迟.

在游戏的表现很好.而且UDPspeederv2也起到了作用.

但是问题是在平时浏览网页和看油管上.如果shadowsocks的UDP服务器和主服务器不串联UDPspeederv2的情况下.看8K极速在48Mbps左右

如果我串联了UDPspeederv2之后.我看油管极速顶多在10Mbps.

原因我看了路由器的top发现,
如果不串连.shadowsocks的进程占用CPU是25%左右.
如果    串连.shadowsocks的进程占用CPU是25%左右.但是UDPspeederv2也是占用25%,

而我在游戏里面.UDPspeederv2的占用只有2%-5%左右.

我奇怪在这里.明明看油管.看视频走的是TCP.为什么UDP通道的UDPspeederv2会占用那么高.

希望作者可以为我解答一下或者给予我一个方案,感谢

**Comment by honwen** [comment]
Try disable QUIC (Quick `UDP` Internet Connections) protocol in Google Chrome
https://kb.fortinet.com/kb/viewContent.do?externalId=FD36680&sliceId=1

**Comment by thisdk** [comment]
thanks!!!
